import type {
  MatchDefinition,
  MatchRecord,
  MatchScoreCoverage
} from "../core/types.js";
import {
  CuratedReplayError,
  renderCuratedReplayModule,
  validateCuratedReplayMatch
} from "./curated-replay.js";

const PARTIAL_LABEL_SUFFIX = " · partial score coverage";

function isScoreRecord(record: MatchRecord): boolean {
  return record.sourceOrder?.domain === "TXLINE_SCORES";
}

export function applyDisclosedPartialCoverage(
  match: MatchDefinition,
  coverage: MatchScoreCoverage
): MatchDefinition {
  const scoreRecords = match.records.filter(isScoreRecord);
  const firstScore = scoreRecords[0];
  if (
    firstScore === undefined ||
    firstScore.kind !== "recovery" ||
    firstScore.sourceTimestamp !== match.kickoffTimestamp ||
    firstScore.snapshot.score.home !== 0 ||
    firstScore.snapshot.score.away !== 0
  ) {
    throw new CuratedReplayError(
      "CURATED_PARTIAL_BASELINE_INVALID",
      "Partial score coverage required a local 0-0 recovery baseline at kickoff."
    );
  }

  let localKickoffMarked = false;
  const records = match.records.map((record) => {
    if (record.recordId === firstScore.recordId) {
      return {
        ...record,
        provenance: "SYNTHETIC" as const,
        recoveryReason:
          "Local structural 0-0 kickoff baseline; TxLINE score archive begins later"
      };
    }
    if (
      !localKickoffMarked &&
      isScoreRecord(record) &&
      record.kind === "event" &&
      record.eventType === "KICKOFF" &&
      record.sourceTimestamp === match.kickoffTimestamp
    ) {
      localKickoffMarked = true;
      return { ...record, provenance: "SYNTHETIC" as const };
    }
    return record;
  });

  const disclosed: MatchDefinition = {
    ...match,
    label: match.label.endsWith(PARTIAL_LABEL_SUFFIX)
      ? match.label
      : `${match.label}${PARTIAL_LABEL_SUFFIX}`,
    coverage,
    records
  };
  validateDisclosedCuratedReplayMatch(disclosed);
  return disclosed;
}

export function validateDisclosedCuratedReplayMatch(
  match: MatchDefinition
): void {
  const coverage = match.coverage;
  if (coverage === undefined) {
    validateCuratedReplayMatch(match);
    return;
  }
  if (
    coverage.scoreHistory !== "PARTIAL_OPENING" ||
    coverage.openingBaseline !== "LOCAL_STRUCTURAL_0_0" ||
    !Number.isSafeInteger(coverage.providerScoreStartTimestamp) ||
    coverage.providerScoreStartTimestamp <= match.kickoffTimestamp ||
    coverage.providerScoreStartTimestamp > match.liveEdgeTimestamp
  ) {
    throw new CuratedReplayError(
      "CURATED_PARTIAL_COVERAGE_INVALID",
      "Partial score coverage metadata was invalid."
    );
  }

  const canonical: MatchDefinition = {
    ...match,
    records: match.records.map((record) => ({
      ...record,
      provenance: "TXLINE" as const
    }))
  };
  delete canonical.coverage;
  validateCuratedReplayMatch(canonical);

  const scoreRecords = match.records.filter(isScoreRecord);
  const baseline = scoreRecords[0];
  if (
    baseline === undefined ||
    baseline.kind !== "recovery" ||
    baseline.provenance !== "SYNTHETIC" ||
    baseline.sourceTimestamp !== match.kickoffTimestamp ||
    baseline.snapshot.score.home !== 0 ||
    baseline.snapshot.score.away !== 0
  ) {
    throw new CuratedReplayError(
      "CURATED_PARTIAL_BASELINE_INVALID",
      "The disclosed local score baseline was invalid."
    );
  }

  const syntheticScoreRecords = scoreRecords.filter(
    (record) => record.provenance === "SYNTHETIC"
  );
  if (
    syntheticScoreRecords.some(
      (record) =>
        record.recordId !== baseline.recordId &&
        !(
          record.kind === "event" &&
          record.eventType === "KICKOFF" &&
          record.sourceTimestamp === match.kickoffTimestamp
        )
    )
  ) {
    throw new CuratedReplayError(
      "CURATED_PARTIAL_PROVENANCE_INVALID",
      "Only the structural baseline and kickoff may use local provenance."
    );
  }

  const providerStart = scoreRecords.find(
    (record) =>
      record.provenance === "TXLINE" &&
      record.sourceTimestamp === coverage.providerScoreStartTimestamp
  );
  if (providerStart === undefined || providerStart.kind !== "recovery") {
    throw new CuratedReplayError(
      "CURATED_PARTIAL_PROVIDER_START_MISSING",
      "No trusted TxLINE recovery matched the disclosed provider coverage start."
    );
  }
}

export function renderDisclosedCuratedReplayModule(
  match: MatchDefinition
): string {
  if (match.coverage === undefined) {
    return renderCuratedReplayModule(match);
  }
  validateDisclosedCuratedReplayMatch(match);
  return [
    'import type { MatchDefinition } from "../core/types.js";',
    "",
    "/**",
    " * Generated by the authenticated curated completed-match exporter.",
    " * Contains only the allowlisted MatchShift product model: no raw payload,",
    " * provider fixture/message identifiers, credentials, or downloadable feed.",
    " * Partial score coverage is explicitly disclosed in the match metadata.",
    " */",
    `export const CURATED_REAL_MATCH: MatchDefinition = ${JSON.stringify(match, null, 2)};`,
    ""
  ].join("\n");
}
